version: "3.8"

services:
  logs_db:
    container_name: logs_db
    image: postgres:14-alpine
    volumes:
      - ./docker-volumes/pgdata:/var/lib/postgresql/data:delegated
    ports:
      - "5432:5432"
    env_file: .env
