version: "3.7"

services:
  logs_db:
    container_name: logs_db
    image: postgres:14-alpine
    volumes:
      - ./docker-volumes/pgdata:/var/lib/postgresql/data:delegated
    ports:
      - "5433:5432"
    env_file:
      - prod.env

  logs_api:
    container_name: logs_api
    build:
      context: .
    volumes:
      - ./docker-volumes/static:/app/static:delegated
    ports:
      - "8000:8000"
    depends_on:
      - logs_db
    env_file: prod.env
